---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: instance
    box: fedora/32-cloud-base
    memory: 512
    cpus: 1
provisioner:
  name: ansible
verifier:
  name: ansible
